### ISSUE TITLE
Installation is Broken - Tested with P8 and P9

### ISSUE THREAD

**Issue by sanjayminni** [astares/Seaside-Bootstrap4#7]
Hi

Unable to install the package - Tried with Pharo 8 & 9

**Comment by astares** [comment]
@sanjayminni Can you be more specific or put a screenshot here

**Comment by astares** [comment]
I tried: loads fine in a fresh P9 image when following the instructions given on project page.

**Comment by sanjayminni** [comment]
I'll recheck.

**Comment by sanjayminni** [comment]
I am sorry,
seems an incorrect report,
Now its working fine in P8 and P9
It wasn't then and it was so predictable / repeatable that i did not keep a screen shot. Must have been some temporary issue in my machine.

anyway will close for now
and once again sorry for the bother
regards

**Comment by astares** [comment]
@sanjayminni No problem. Feel free to report issues but always give details to reproduce.
